记录时间：2017-04-08 10:29:31,291 线程ID:[11] 日志级别：ERROR 出错类：Error property:[(null)] - 错误描述：未将对象引用设置到对象的实例。
HangFire_Infrastructure

   在 HangFire_Infrastructure.CustomAttributeClassLibrary.CustomRequestAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 D:\GitHub\HangFireDemo\HangFire_Infrastructure\CustomAttributeClassLibrary\CustomRequestAuthorizeAttribute.cs:行号 35
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
记录时间：2017-04-08 10:29:31,316 线程ID:[11] 日志级别：ERROR 出错类：Error property:[(null)] - 错误描述：未将对象引用设置到对象的实例。
HangFire_Infrastructure

   在 HangFire_Infrastructure.CustomAttributeClassLibrary.CustomRequestAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 D:\GitHub\HangFireDemo\HangFire_Infrastructure\CustomAttributeClassLibrary\CustomRequestAuthorizeAttribute.cs:行号 35
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
